version: "3.5"

services:
  temporal:
    environment:
      DB: postgresql
      DB_PORT: "5432"
      POSTGRES_USER: temporal
      POSTGRES_PWD: temporal
      POSTGRES_SEEDS: temporal-postgresql
      DYNAMIC_CONFIG_FILE_PATH: config/dynamicconfig/development.yaml
    image: temporalio/auto-setup:1.13.4
    networks:
      - ea-network
    ports:
      - 7233:7233
    depends_on:
      - temporal-postgresql

  temporal-admin-tools:
    depends_on:
      - temporal
    environment:
      TEMPORAL_CLI_ADDRESS: temporal:7233
    image: temporalio/admin-tools:1.13.4
    networks:
      - ea-network
    stdin_open: true
    tty: true
  temporal-web:
    profiles: [ 'temporal' ]
    depends_on:
      - temporal
    environment:
      TEMPORAL_GRPC_ENDPOINT: temporal:7233
      TEMPORAL_PERMIT_WRITE_API: "true"
    image: temporalio/web:1.13.0
    networks:
      - ea-network
    ports:
      - 8088:8088

  temporal-postgresql:
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    image: postgres:12
    command: postgres -c 'max_connections=2000'
    networks:
      - ea-network
      
networks:
  ea-network:
    driver: bridge
    name: ea-network